#!/bin/bash
# SATNOGS_PRE_OBSERVATION_SCRIPT="satnogs-pre {{ID}} {{FREQ}} {{TLE}} {{TIMESTAMP}} {{BAUD}} {{SCRIPT_NAME}}"


nohup rtl_biast -b 1
echo "bias tee on"
bandscan.sh stop
direwolf.sh stop
grsat.py start "$@"
satdump.sh start "$@"
meteor.sh start "$@"
if [[ "${GPIO_ENABLE^^}" =~ (TRUE|YES|1) ]]; then
  gpio.py -f "${2}"
fi
