#!/bin/bash
# SATNOGS_PRE_OBSERVATION_SCRIPT="satnogs-pre {{ID}} {{FREQ}} {{TLE}} {{TIMESTAMP}} {{BAUD}} {{SCRIPT_NAME}}"

if [[ "${BIAST_ENABLE^^}" =~ (TRUE|YES|1) ]]; then
  rtl_biast -b 1 &> /dev/null
  echo "bias tee on"
fi

bandscan.sh stop
direwolf.sh stop
grsat.py start "$@"
satdump.sh start "$@"
meteor.sh start "$@"
if [[ "${GPIO_ENABLE^^}" =~ (TRUE|YES|1) ]]; then
  gpio.py -f "${2}"
fi
