services:
  satnogs_auto_scheduler:
    build:
      context: .
    image: satnogs-auto-scheduler
    user: '999'
    read_only: true
#    command: "schedule_single_station.py -s 4063 -T"
    entrypoint: "/data/entrypoint.sh"
    env_file:
      - ./station.env
    volumes:
      - type: 'tmpfs'
        target: '/tmp'
      - "./data:/data"